//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int l_Id { get; set; }
        public string l_type { get; set; }
        public int l_amount { get; set; }
        public string l_duration { get; set; }
        public int l_roi { get; set; }
        public int borrower_b_Id { get; set; }
    
        public virtual borrower borrower { get; set; }
    }
}
